### ISSUE TITLE
Comparing Signed and Unsigned Serial Numbers

### ISSUE THREAD

**Issue by ghost** [reitermarkus/DDC.swift#2]
Based on an issue I came across with ddcctl (and subsequently found a solution for, see here: https://github.com/kfix/ddcctl/issues/53#issuecomment-525921778).

I believe the same issue is present in the DDC.swift file, around the servicePort function. I'm not super familiar with Swift, but it looks like the guard statements are doing the same thing with comparing a uint32_t to a CFIndex (signed int). I am getting the "No service port found for display with ID %d." error on line 562 in MonitorControl, so it looks like it's failing in the same place.

As mentioned in the link, my Acer monitor does work with ddcctl after making that change.

**Comment by ghost** [comment]
Ok, I just built MonitorControl and I can confirm that doing this in the guard statements solves the problem, and now my monitor works with MonitorControl:

      let unsigned_vendorId = UInt32(bitPattern: Int32(vendorId));
      guard unsigned_vendorId == CGDisplayVendorNumber(displayId) else {
        os_log("Service port vendor ID %ld differs from display vendor ID %ld.", type: .debug, vendorId, CGDisplayVendorNumber(displayId))
        continue
      }

      let unsigned_productId = UInt32(bitPattern: Int32(productId));
      guard unsigned_productId == CGDisplayModelNumber(displayId) else {
        os_log("Service port product ID %ld differs from display product ID %ld.", type: .debug, productId, CGDisplayModelNumber(displayId))
        continue
      }

      let unsigned_serial = UInt32(bitPattern: Int32(serialNumber));
      guard unsigned_serial == CGDisplaySerialNumber(displayId) else {
        os_log("Service port serial number %ld differs from display serial number %ld.", type: .debug, serialNumber, CGDisplaySerialNumber(displayId))
        continue
      }

**Comment by reitermarkus** [comment]
Can you give example numbers with which it fails?

**Comment by ghost** [comment]
Any 32-bit number with a "1" in bit position 31 should do it. I saw in XCode a very large negative number was being compared with a very large positive number, but both were actually the same number being represented differently. 

More specifically, the signed number was being sign-extended in the compiler's internal representation, so the bit patterns weren't matching any more during the comparison. I can't give you the exact number because, well, it's a serial number, but something like 0x90000000 would demonstrate the problem. Unsigned it's 2,415,919,104, but signed it's -1,879,048,192. On a 64-bit system, register sizes are 64-bits, so the CPU has to sign-extend the number to fit in a 64-bit register, and you get 0b000..010010...0 compared against 0b111..110010...0, which fails a comparison. I'm not sure at which level of abstraction this crops up here (it's hard to tell without looking at the assembly generated by the compiler), but fundamentally this is why comparing signed integers against unsigned integers is pretty much always classified as undefined behavior.

**Comment by reitermarkus** [comment]
Thanks, just wanted to be sure that converting using `bitPattern` is indeed the right solution here.

Should be fixed by https://github.com/reitermarkus/DDC.swift/commit/3de17d9915b547a0516d613f58d7fa0d8281cd80.
