### ISSUE TITLE
Wrong addressing with multiple identical monitors

### ISSUE THREAD

**Issue by r1kaj** [reitermarkus/DDC.swift#4]
#### Issue description
This library seems to have some issues with multiple identical monitors. When I try to send a command to both monitors, the command gets send to the first monitor twice instead of once to both monitors.

#### System information
- Monitors: 2x HP Envy 27s (both connected via DP)
- Graphics card: Radeon RX580
- macOS Version: 10.15 Catalina/ 10.14 Mojave
- CPU: i7 8700k

There are more people with different setups affected by this issue over at the0neyouseek/MonitorControl/issues/49. So this isn't limited to a specific monitor model.

#### Steps to reproduce the issue
I can reproduce this issue with this loop:
```
for screen in NSScreen.screens{
    debugPrint("========================================")
    DDC(for: screen)?.write(command: .brightness, value: 100)
}
```

Output when running the loop above:
> "========================================"
> 2019-10-11 12:36:34.408868+0200 xctest[6557:52535] Service port vendor ID 0 differs from display product ID 8718.
> 2019-10-11 12:36:34.410768+0200 xctest[6557:52535] Framebuffer: AMDFramebufferVIB
> 2019-10-11 12:36:34.410792+0200 xctest[6557:52535] Location: IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/PEG0@1/IOPP/PEGP@0/ATY,AMD,RadeonFramebuffer@1/AMDFramebufferVIB/display0/AppleDisplay
> 2019-10-11 12:36:34.410801+0200 xctest[6557:52535] Vendor ID: 8718, Product ID: 13334, Serial Number: 0
> 2019-10-11 12:36:34.410843+0200 xctest[6557:52535] Unit Number: 1
> 2019-10-11 12:36:34.410855+0200 xctest[6557:52535] Service Port: 16391
> 2019-10-11 12:36:34.411274+0200 xctest[6557:52535] kIOI2CDDCciReplyTransactionType is supported.
> "========================================"
> 2019-10-11 12:36:34.412884+0200 xctest[6557:52535] Service port vendor ID 0 differs from display product ID 8718.
> 2019-10-11 12:36:34.414279+0200 xctest[6557:52535] Framebuffer: AMDFramebufferVIB
> 2019-10-11 12:36:34.414297+0200 xctest[6557:52535] Location: IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/PEG0@1/IOPP/PEGP@0/ATY,AMD,RadeonFramebuffer@1/AMDFramebufferVIB/display0/AppleDisplay
> 2019-10-11 12:36:34.414306+0200 xctest[6557:52535] Vendor ID: 8718, Product ID: 13334, Serial Number: 0
> 2019-10-11 12:36:34.414339+0200 xctest[6557:52535] Unit Number: 2
> 2019-10-11 12:36:34.414350+0200 xctest[6557:52535] Service Port: 16183
> 2019-10-11 12:36:34.414678+0200 xctest[6557:52535] kIOI2CDDCciReplyTransactionType is supported.

I'm only able to change the brightness of the second monitor when I disconnect the first monitor.

#### What's the expected result?
The brightness of both monitors should be set to 100%

#### What's the actual result?
Just the brightness of the first monitor gets set to 100%. The brightness of the second monitor stays the same.

**Comment by r1kaj** [comment]
This may be an issue of Apples IOKit Library.

I noticed that the `IODisplayCreateInfoDictionary` function returns the same location for both displays, even though a different port is passed to the function when it gets called the second time.

The `kIODisplayLocationKey` key in the dict is: 
> IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/PEG0@1/IOPP/PEGP@0/ATY,AMD,RadeonFramebuffer@1/AMDFramebufferVIB/display0/AppleDisplay

If i understand this issue correctly the second location should be (according to my windowserver.plist):
> IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/PEG0@1/IOPP/PEGP@0/ATY,AMD,RadeonFramebuffer@2/AMDFramebufferVIB

(Full output of [defaults read /Library/Preferences/com.apple.windowserver.plist](https://gist.github.com/r1sim/3b5a6487ee2117deb7385c80aae419c5))


The second thing i noticed is that the [IOFBCopyI2CInterfaceForBus](https://github.com/reitermarkus/DDC.swift/blob/master/DDC/DDC.swift#L472) function opens the same interface for each framebuffer.

Unfortunately I don't have an additional monitor to see how the correct output of these functions would look like and Apples documentation is not as helpful as i would like it to be.

**Comment by varanauskas** [comment]
Another library based on kfix/ddcctl has a partially working workaround for this issue that could hopefully be ported here:
https://github.com/fnesveda/ExternalDisplayBrightness/commit/e20bfb801cf747bea28884a92559f817a27a1aff

**Comment by mikelow** [comment]
Re @varanauskas suggestion: I was able to simply copy in `getIOFramebufferPort()` into DDC from the above project (and its helper function `framebufferPortMatchesDisplay()`) as a repalacement for `servicePort()` and it compiled without issue. This fixed the bug as it was occurring in [MonitorControl](https://github.com/MonitorControl/MonitorControl).

I'd expect a proper adaptation of the linked code would be easy for those familiar with DDC.

**Comment by leo150** [comment]
Opened a #5 with a fix. Please review if possible.

**Comment by reitermarkus** [comment]
Should be fixed by https://github.com/reitermarkus/DDC.swift/pull/5.
